/**
 * In the future, this will be a parser for Chatbook .html files
 * generated by Twine 2. It will convert the items to a JSON
 * structure
 */

console.error("This is a Twine2 Format Module");
throw new Error("Not Implemented");
